In [1]:
import pandas as pd
pd.options.display.max_colwidth = 100

In [2]:
# load in Alice in Wonderland text
alice_file = '../Resources/alice.txt'

alice_df = pd.read_csv(alice_file, sep='\n', header=None)
alice_df.columns = ['text']
alice_df.head()

                                                                       text
0                                          ALICE’S ADVENTURES IN WONDERLAND
1                                           CHAPTER I. Down the Rabbit-Hole
2     Alice was beginning to get very tired of sitting by her sister on the
3  bank, and of having nothing to do: once or twice she had peeped into the
4   book her sister was reading, but it had no pictures or conversations in

In [3]:
# find all lines of text with the strings 'cat', 'hat', and 'eat'
p = r"\s[che]at\s"
alice_df[alice_df['text'].str.contains(p)]

                                                                          text
69     like a mouse, you know. But do cats eat bats, I wonder?’ And here Alice
71       sort of way, ‘Do cats eat bats? Do cats eat bats?’ and sometimes, ‘Do
72       bats eat cats?’ for, you see, as she couldn’t answer either question,
76    did you ever eat a bat?’ when suddenly, thump! thump! down she came upon
164    ‘EAT ME’ were beautifully marked in currants. ‘Well, I’ll eat it,’ said
316     about it. And yet I wish I could show you our cat Dinah: I think you’d
441          The next thing was to eat the comfits: this caused some noise and
526                           she’ll eat a little bird as soon as look at it!’
580       to herself, ‘whenever I eat or drink anything; so I’ll just see what
696       head. ‘If I eat one of these cakes,’ she thought, ‘it’s sure to make
720    hungry, in which case it would be very likely to eat her up in spite of
743          suppose I ought to eat or drink something or other; but the great
747       looked like the right thing to eat or drink under the circumstances.
882     set to work at once to eat some of the other bit. Her chin was pressed
937        child; ‘but little girls eat eggs quite as much as serpents do, you
1033  that did not sneeze, were the cook, and a large cat which was sitting on
1037                                                your cat grins like that?’
1190  ‘Well! I’ve often seen a cat without a grin,’ thought Alice; ‘but a grin
1235         that “I see what I eat” is the same thing as “I eat what I see”!’
1608     ‘A cat may look at a king,’ said Alice. ‘I’ve read that in some book,
1612                                                   have this cat removed!’

In [4]:
# find all lines of text with the strings 'cat', 'hat', and 'eat' that end with a period
p = r"\s[che]at\.$"
alice_df[alice_df['text'].str.contains(p)]

Empty DataFrame
Columns: [text]
Index: []

In [5]:
# find all lines of text with a word that matches the form "w*ll"
p = r"w.ll"
alice_df[alice_df['text'].str.contains(p)]

                                                                          text
7        So she was considering in her own mind (as well as she could, for the
28                                                                       well.
29         Either the well was very deep, or she fell very slowly, for she had
33     looked at the sides of the well, and noticed that they were filled with
117      It was all very well to say ‘Drink me,’ but the wise little Alice was
...                                                                        ...
2114                                                             just as well.
2124     Alice could see, as well as if she were looking over their shoulders,
2219    the officers of the court. (As that is rather a hard word, I will just
2433  sister, as well as she could remember them, all these strange Adventures
2437      Alice got up and ran off, thinking while she ran, as well she might,

[64 rows x 1 columns]